apiVersion: v1
kind: Service
metadata:
  labels:
    app: busybox
  name: busybox
spec:
  clusterIP: None
  selector:
    app: busybox
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  serviceName: busybox
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
          - sleep
          - infinity
        volumeMounts:
        - name: busybox
          mountPath: /busybox
  volumeClaimTemplates:
  - metadata:
      name: busybox
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: openebs-cstor-sc
      resources:
        requests:
          storage: 2Gi