#Use the following YAMLs to create a cStor Storage Pool.
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-disk-pool-striped
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 2Gi
      - name: PoolResourceLimits
        value: |-
            memory: 4Gi
spec:
  name: cstor-disk-pool
  type: disk
  poolSpec:
    poolType: striped
  blockDevices:
    blockDeviceList:
      - blockdevice-6bb13f92472a40f70caa39f44dc9aa9c   # k8s-federated-storage-pool-3leom   53686025728   Unclaimed    Active   64s
      - blockdevice-93b74e5c76521c795679c792cb81d72e   # k8s-federated-storage-pool-3leoq   53686025728   Unclaimed    Active   44s
      - blockdevice-9dac4cb77614f548dd494cd17c0ca84b   # k8s-federated-storage-pool-3leof   53686025728   Unclaimed    Active   19s
---
