apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-jiva-single-node
  annotations:
    openebs.io/cas-type: jiva
    cas.openebs.io/config: |
      - name: ReplicaCount
        value: "1"
      - name: StoragePool
        value: jiva-pool
provisioner: openebs.io/provisioner-iscsi